dist: xenial
sudo: required
install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.59.0/hugo_0.59.0_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
script:
  - rm -rf public 2> /dev/null
  - hugo
before_deploy:
  - openssl aes-256-cbc -K $encrypted_a6c8ec7e25bd_key -iv $encrypted_a6c8ec7e25bd_iv -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip-cleanup: true
  script: rsync -av --quiet --delete-after ${TRAVIS_BUILD_DIR}/public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
env:
  global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.59.0
  - secure: yl3b0D/hWUv1aLk7ATGsZ45ZX9rw5fCll/0CUmAyXD9njjza+FIUb3u2t/2KZ6vx4F9WfNJr6tYp5Q6ixNj/VCPtg4RFUJv5/zayyMPx8v4s7IPIZfQDfEBahg/+hH8HvaecvBEQlp894f+6R2u0FgEfaeS1aQ87N1sr0MsGp3xEKEZVCnhewNhZkmWD5gIXwFfmIHN0bLuZr74F8lSV8N54n0P3wQhysy9M0t9H5Epvg8yAmt9x2hlcxJZ4LFO2miXaNGkvLuSSi5FFpEHNOeeLEfKTbNC52gJGQQ8nnU3+xxuMfBJF5emFeH8a/g/hFtMnh/ZpJLoHmjlT7lmaVD28P/FBYbmtpsRjZwuhN9gBgdyHPf4F+FE4FmQj0WY9EB3ix/iRHGRoOIndO3t/B2UqDd6WZT94qtXc47xvMffcXGiGqrmSN9gKQnTR9Dqa9cEgI5MI6v12AfmgtBJY7wXaqjH50YfB5EaeJqkHO/w4XH7ZwaRESrLrJ2Y4sZfrB9uSbaTFxmapIIPtcUEwB6JWjj+W6AA88OABozfqdKVsla2hu9UbMyFKi2DCqsNgamCg99FUkTYIS8YRprEGrzAnMHQsqJewY4Z15wLpABDIo0nncM9CEteYyh8FgyMGC+pEs2aWU5tXUNNd0g0thurJ80bTJewuG1f452zItms=
  - secure: joDroYYr0AtZngK8q/g7n4yAXZuZbTz7+nsDIIxAacKkntQEIo66eqraFQ09zkWJ8wblxmPrAcyWX9GNpdIA6UxjSo3SclvJuxmtmlBM0+pFgrP4VBgWmws/eiEqOm3RjMpW3Vf7g03HcxkQzUfFg3t2HM+BeK218MCBntvFt6Gfb84Oin2tMJEUT78U9pvkKH6weVtNosfPclcqHEKyGX/U1mtuzdOy9imKfiX4TB7x5qcymo6NfJ/wH1IaNbqBtkc6IA4LFu7vzeMtIyKrpbTBLdb6JQiaJsWvZhKge4m2mPHR0CmZBju93hVTTXjCtyklNWufXgwGDwmsfVqdEeSSorMMXHsA/csKqyHFdqNypuTZR7wmYm0USb3R5+BcSpCziHl75tK766wRw2lvbf88+KYJM5+/b0ilwGjMsMWun7JPy+23YnAjhcNRHSHw0Gb4dH5KS8UqbsUODxBaN/94Ec3T7NyI4ws0wu5mBwkdyAiHwseeWhxTAVxXe471B6kx5yzuEL3UP5jdVzgd6J4IdpFqeZSJ02xkY2JVG5Wx4FBHABvPnszr+LX3jde5hHoedRrOFJC51o3ZEpYs/M9k6BDnA+9kJhK60JdEzFeqEYvsfy0/LbRPG2iVSbpqO4/61VeGktaAaWC+WSNC+I1qCVo/ySNA7X1lLt6d9L8=
  - secure: YFjF42+4dvQ+UYEGIaUL/StXLDNqXsRqk3i4CDwwMwLNBkDlKtirczPJJVZf7jjWPhr0ZJ2AGzQmEAvJLN79jTkBoNKjcRgro4VXMd5fKgd1ubnfGHH0f6sc+O1goEToCVYrLFGLOola+DrSd7kccH85Uu3nup1EOy0wqGMbAwyEXpr1cXqqcgarqSFK4N0oi86sk/tcIfsgyE+CeBLw6hnFFTp+ofKqvz8sO8WgIYJEccFwJQDIQsw4Xz9rVjMhRJebGt4fLXtJg1jFFAcrTqISqSiBDrSQ1A0DgjkOgojo8NoLac3GfVItSbjc6lNcKoJkwu81eJPEfx3gHhGX2T5Nuaum4ozlvNYN5+OwFT53X76h1oJkltJrMiQA0LwRg0YGu8nWHdiNAVVzeAxxwil0ol5oNriMZtXOZVTPaWvBa0Cz3Qn4NNS+J/YjLLsN73zk8n/RfjuMTpRBeUOJXsRtbVNGbqyyTv0oLahIC6GOzmlYPaXhGaYUL5v1jotpNr3oPaDslNDw3zwsfd61Ex1POBc0H88L1k39wna6hWK3W4Sbu9C9q8gUdUPbn1LGJT48wecrSl4wSCq0VExBqpcD8Wx7XJWJB8G0uinrlfDaZHuZHO8IRiFCzStvL5zRchEC6r+BiEU5z3cplacnhHAze4/G3XW/UWwGuUHz6nU=
