dist: xenial
sudo: required
install:
- wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.59.0/hugo_0.59.0_Linux-64bit.deb
- sudo dpkg -i /tmp/hugo.deb
script:
- hugo
before_deploy:
- openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy/deploy_rsa.enc
  -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip-cleanup: true
  script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
env:
  global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.59.0
  - secure: "<a long string of random looking ASCII chars ending with an equal sign>"
  - secure: "<another long ASCII string ending with an equal sign>"
  - secure: "<and another long ASCII string ending with an equal sign>"
before_install:
- openssl aes-256-cbc -K $encrypted_a6c8ec7e25bd_key -iv $encrypted_a6c8ec7e25bd_iv
  -in deploy_rsa.enc -out deploy_rsa -d
